services:
  frontend:
    image: node:20
    working_dir: /app
    volumes:
      - ./front:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    environment:
      - VITE_MANAGMENT_URL=http://localhost:5001
    command: sh -c "npm install && npm run dev" 
    depends_on:
     managment:
      condition: service_healthy
    networks:
      - app-network

  managment:
    image: node:20
    working_dir: /app
    volumes:
      - ./pishing-managment:/app
      - /app/node_modules
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MONGO_URL=mongodb://mongo:27017
      - JWT_SECRET={JWT_SECRET}
      - PHISHING_SIMULATOR_URL=http://localhost:5000
    command: sh -c "npm install && npm run start:dev"
    depends_on:
      - mongo
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5001"]
      interval: 30s
      timeout: 10s
      retries: 3

  simulation:
    image: node:20
    working_dir: /app
    volumes:
      - ./pishing-simulation:/app
      - /app/node_modules
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URL=mongodb://mongo:27017
      - EMAIL_USER={EMAIL_USER}
      - APP_URL=http://localhost:5000
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
    command: sh -c "npm install && npm run start:dev"
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network

volumes:
  mongo-data:
  node_modules:

networks:
  app-network:
    driver: bridge